/*
 * generated by Xtext 2.36.0
 */
package org.xtext.chalmers.qualitybt;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class QualityBtStandaloneSetup extends QualityBtStandaloneSetupGenerated {

	public static void doSetup() {
		new QualityBtStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
