/*
 * generated by Xtext 2.36.0
 */
package org.xtext.chalmers.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.chalmers.parser.antlr.internal.InternalQualityBtCppParser;
import org.xtext.chalmers.services.QualityBtCppGrammarAccess;

public class QualityBtCppParser extends AbstractAntlrParser {

	@Inject
	private QualityBtCppGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalQualityBtCppParser createParser(XtextTokenStream stream) {
		return new InternalQualityBtCppParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Root";
	}

	public QualityBtCppGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(QualityBtCppGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
