/*
 * generated by Xtext 2.36.0
 */
package org.xtext.chalmers.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class QualityBtCppAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/chalmers/parser/antlr/internal/InternalQualityBtCpp.tokens");
	}
}
