/*
 * generated by Xtext 2.36.0
 */
package org.xtext.btcpp.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.btcpp.QualityBtCppRuntimeModule;
import org.xtext.btcpp.QualityBtCppStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class QualityBtCppIdeSetup extends QualityBtCppStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new QualityBtCppRuntimeModule(), new QualityBtCppIdeModule()));
	}
	
}
