/*
 * generated by Xtext 2.36.0
 */
package org.xtext.chalmers.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractQualityBtCppScopeProvider extends DelegatingScopeProvider {
}
