/*
 * generated by Xtext 2.36.0
 */
package org.xtext.btcpp;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QualityBtCppRuntimeModule extends AbstractQualityBtCppRuntimeModule {
}
