/*
 * generated by Xtext 2.36.0
 */
package org.xtext.btcpp;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class QualityBtCppStandaloneSetup extends QualityBtCppStandaloneSetupGenerated {

	public static void doSetup() {
		new QualityBtCppStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
