/*
 * generated by Xtext 2.36.0
 */
package org.xtext.chalmers.qualitybt.parser.antlr;

import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;
import org.xtext.chalmers.qualitybt.parser.antlr.internal.InternalQualityBtParser;

public class QualityBtTokenSource extends AbstractIndentationTokenSource {

	public QualityBtTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalQualityBtParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalQualityBtParser.RULE_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalQualityBtParser.RULE_END;
	}

}
