/*
 * generated by Xtext 2.36.0
 */
package org.xtext.chalmers.ide;


/**
 * Use this class to register ide components.
 */
public class QualityBtCppIdeModule extends AbstractQualityBtCppIdeModule {
}
