/*
 * generated by Xtext 2.36.0
 */
package org.xtext.chalmers.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.chalmers.qualitybtcpp.ui.internal.QualitybtcppActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class QualityBtCppExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(QualitybtcppActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		QualitybtcppActivator activator = QualitybtcppActivator.getInstance();
		return activator != null ? activator.getInjector(QualitybtcppActivator.ORG_XTEXT_CHALMERS_QUALITYBTCPP) : null;
	}

}
