/*
 * generated by Xtext 2.36.0
 */
package org.xtext.chalmers.qualitybt.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class QualityBtAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/chalmers/qualitybt/parser/antlr/internal/InternalQualityBtParser.tokens");
	}
}
