<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="btcpp" nsURI="http://www.example.org/btcpp" nsPrefix="btcpp">
  <eClassifiers xsi:type="ecore:EClass" name="BehaviorTree">
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" lowerBound="1" upperBound="-1"
        eType="#//TreeNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TreeNode" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AnyAttribute" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="satisfices" upperBound="-1"
        eType="#//Quality"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="satisfies" upperBound="-1"
        eType="#//QualityRequirement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlNode" abstract="true" eSuperTypes="#//TreeNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" lowerBound="1" upperBound="-1"
        eType="#//TreeNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DecoratorNode" abstract="true" eSuperTypes="#//TreeNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" lowerBound="1" eType="#//TreeNode"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlwaysFailureNode" eSuperTypes="#//SyncActionNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlwaysSuccessNode" eSuperTypes="#//SyncActionNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="SetBlackboardNode" eSuperTypes="#//SyncActionNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output_key" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FallbackNode" eSuperTypes="#//ControlNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="IfThenElseNode" eSuperTypes="#//ControlNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ManualSelectorNode" eSuperTypes="#//ControlNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParallelNode" eSuperTypes="#//ControlNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceWithMemoryNode" eSuperTypes="#//ControlNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="SwitchNode" eSuperTypes="#//ControlNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReactiveFallbackNode" eSuperTypes="#//ControlNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="WhileDoElseNode" eSuperTypes="#//ControlNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReactiveSequenceNode" eSuperTypes="#//ControlNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceNode" eSuperTypes="#//ControlNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimeoutNode" eSuperTypes="#//DecoratorNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="msec" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeepRunningUntilFailureNode" eSuperTypes="#//DecoratorNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="InverterNode" eSuperTypes="#//DecoratorNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForceSuccessNode" eSuperTypes="#//DecoratorNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForceFailureNode" eSuperTypes="#//DecoratorNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="RepeatNode" eSuperTypes="#//DecoratorNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="num_cycles" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionNode" abstract="true" eSuperTypes="#//LeafNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubTree" eSuperTypes="#//TreeNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" upperBound="-1"
        eType="#//TreeNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LeafNode" abstract="true" eSuperTypes="#//TreeNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActionNodeBase" abstract="true" eSuperTypes="#//LeafNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ScriptNode" eSuperTypes="#//SyncActionNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ScriptConditionNode" eSuperTypes="#//ConditionNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="RetryNode" eSuperTypes="#//DecoratorNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="num_attempts" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviortrees" lowerBound="1"
        upperBound="-1" eType="#//BehaviorTree" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="main_tree_to_execute" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QualityRequirement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Quality">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualityreq" upperBound="-1"
        eType="#//QualityRequirement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParallelAllNode" eSuperTypes="#//ControlNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="DelayNode" eSuperTypes="#//DecoratorNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay_msec" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreconditionNode" eSuperTypes="#//DecoratorNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="EntryUpdatedDecoratorNode" eSuperTypes="#//DecoratorNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="RunOnceNode" eSuperTypes="#//DecoratorNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="LoopNode" eSuperTypes="#//DecoratorNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConsumeQueueNode" eSuperTypes="#//DecoratorNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="TestNode" eSuperTypes="#//StatefulActionNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="EntryUpdatedActionNode" eSuperTypes="#//SyncActionNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnsetBlackboardNode" eSuperTypes="#//SyncActionNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="SyncActionNode" abstract="true" eSuperTypes="#//ActionNodeBase"/>
  <eClassifiers xsi:type="ecore:EClass" name="ThreadedActionNode" eSuperTypes="#//ActionNodeBase"/>
  <eClassifiers xsi:type="ecore:EClass" name="StatefulActionNode" abstract="true"
      eSuperTypes="#//AsynchActionNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="CoroActionNode" eSuperTypes="#//AsynchActionNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="AsynchActionNode" abstract="true" eSuperTypes="#//ActionNodeBase"/>
  <eClassifiers xsi:type="ecore:EClass" name="SleepNode" eSuperTypes="#//StatefulActionNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="PopFromQueueNode" eSuperTypes="#//SyncActionNode"/>
</ecore:EPackage>
