/*
 * generated by Xtext 2.36.0
 */
package org.xtext.chalmers.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class QualityBtCppUiModule extends AbstractQualityBtCppUiModule {

	public QualityBtCppUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
